### ISSUE TITLE
if no hits for a gene the output is confusing

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_blast#26] opened 2018-11-08 15:24 UTC
Consider this gene page with no hits

![screen shot 2018-11-08 at 10 15 49 am](https://user-images.githubusercontent.com/7063154/48207991-d6bdae00-e33f-11e8-931a-e485f93681dc.png)

Note the blank db name, and the figure drawn despite no hits (which is confusing).

https://github.com/tripal/tripal_analysis_blast/blob/8e84989a6ba65bbc19cef62f128c18411be93326/includes/TripalFields/format__blast_results/format__blast_results_formatter.inc#L16-L22

Note that items isnt empty so the above code doesnt return.  I instead propose:

https://github.com/tripal/tripal_analysis_blast/blob/8e84989a6ba65bbc19cef62f128c18411be93326/includes/TripalFields/format__blast_results/format__blast_results_formatter.inc#L69-L80

![screen shot 2018-11-08 at 10 23 13 am](https://user-images.githubusercontent.com/7063154/48208222-564b7d00-e340-11e8-914d-fd7923a6407d.png)

As you can see, in this case, our parsed result is empty.  So in the above code, lets add a check for `->db` and add a "no db" in the db name.  And for `      $hits_array    = $blast_result->hits_array;`, return with a message similar to "No hits" without drawing the graph.

**Comment by almasaeed2010** [comment] 2018-11-12 15:02
We have many genes on the live site affected by this issue. Should I submit a PR implementing your suggestions?

**Comment by bradfordcondon** [comment] 2018-11-12 15:05
if youre able to thats great.  I imagine we would want someone else who uses the module to give feedback.  @spficklin @abretaud you all are the two contributors listed for this module, what do you think?


I think the blank dB name is a bug and can be PR'd without much discussion.  Drawing or not drawing the diagram, though, i'd like a 👍 / 👎

**Comment by spficklin** [comment] 2018-11-14 00:39
agreed...

**Comment by spficklin** [comment] 2018-11-14 17:21
I think drawing the diagram is fine if it indicates there are no matches in some way.  But if it's easier to not draw it and it is clear that there are no matches for the user then I'm okay with it not being drawn.

**Comment by almasaeed2010** [comment] 2018-11-14 18:27
Sounds good to me. I am gonna work on this and submit a PR.

**Comment by spficklin** [comment] 2018-12-30 23:13
@almasaeed2010 it looks like you committed a fix on Nov 15?  I don't see a PR, though.  No worries if this is fixed for you can you close this out?

**Comment by almasaeed2010** [comment] 2019-03-15 14:18
Wow I completely forgot about this issue! Sorry!

I believe the issue is fixed since I no longer see it on our live site.

Thanks!

**Closed as completed by almasaeed2010** 2019-03-15 14:18 UTC
Labels: enhancement
